name: coding-metrics
description: Run the coding-metrics app via its Dockerfile as a Docker-based GitHub Action
author: Jack Plowman

# Optional: tweak the Marketplace appearance if/when published
branding:
  icon: "code"
  color: "blue"

runs:
  using: "docker"
  image: "Dockerfile"
  post-entrypoint: '/post_entrypoint.sh'

inputs:
  github_token:
    description: "The GitHub token"
    required: true
  workflow_github_token:
    description: "The GitHub token for the workflow"
    required: false
    default: ${{ github.token }}
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
  test_mode:
    description: "Enable test mode"
    required: false
    default: "false"
  repository:
    description: "The GitHub repository (owner/repo)"
    required: true
    default: ${{ github.repository }}
  output_branch:
    description: "The branch to commit the changes to"
    required: true
    default: "main"
  output_file_name:
    description: "The name of the output file"
    required: true
    default: "output.svg"
  commit_message:
    description: "The commit message"
    required: false
    default: "Update Coding Metrics"
  colour_profile:
    description: "Colour profile to use (default, dark, light, github, ocean, sunset, forest, purple)"
    required: false
    default: "default"
