name: "Setup Go Dependencies"
description: "Sets up Go dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Setup Go environment
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: go.mod
    - name: Set up Just
      uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
