name: "Setup Go Dependencies"
description: "Sets up Go dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Setup Go environment
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: go.mod
    - name: Set up Just
      uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0
